#!/bin/bash

if [[ $1 = -s && $# = 2 ]]; then
    dpkg -S "$2" | grep -P "bin/$2(\..*)?$" | grep -P --color "(?<=/)$2"
elif [[ $# = 1 ]]; then
    dpkg -S "$1" | grep 'bin/' | grep -P --color "(?<=/)$1"
else echo Error.
fi
