#!/bin/bash
# List files 'owned' by package.
# 简化 dpkg -L xxx | grep xxx

function help() {
    cat <<EOF
Usage: dpkgl [-b|-m] <package>
    List files 'owned' by package.

    Options:
      -b    only bin files
      -m    only manpage files
      -h    display this help and exit

EOF
} >&2

(($# < 1)) && { help; exit 2; } # 未传参时显示帮助并退出

while getopts 'bmh' OPT; do
    case $OPT in
        b) flagBin=1;;
        m) flagMan=1;;
        \?|h) help; exit 2;;
        *) ;;
    esac
done

shift $((OPTIND - 1))

if [ "$flagBin" ]; then
dpkg -L "$@" | grep -F 'bin/' | grep --color '[^/]*$'
elif [ "$flagMan" ]; then
dpkg -L "$@" | grep -P 'man/man\d/' | grep --color -P '[^/]*(?=\.\d\.gz)'
else
dpkg -L "$@" | grep -F 'bin/' | grep --color '[^/]*$'
fi
